const array2 =[
["Smartphone", "Smartphone", "Smartphone", "Smartphone", "Smartphone", "Smartphone", "Smartphone", "Smartphone", "Smartphone", "Smartphone"],
["Laptop", "Laptop", "Laptop", "Desktop PC", "Desktop PC", "Desktop PC", "Desktop PC", "Laptop", "Desktop PC", "Laptop"],
["DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera", "DSLR Camera"],
["Washing Machine", "Oven", "Oven", "Oven", "Washing Machine", "Fridge", "Mixer", "Iron", "Fridge", "Vacuum Robot"],
["Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt"],
["T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt"],
["Jacket", "Coat", "Coat", "Leather Jacket", "Coat", "Jacket", "Coat", "Coat", "Coat", "Jacket"],
["Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants"],
["Casual Bag", "Luxury Bag", "Casual Bag", "Luxury Bag", "Luxury Bag", "Luxury Bag", "Golden Earrings", "Silver Earrings", "Golden Earrings", "Star Earrings "],
["Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt", "Shirt"],
["T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt", "T-Shirt"],
["Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket", "Casual Jacket"],
["Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants", "Pants"],
["Watch", "Sunglasses", "Sunglasses", "Sunglasses", "Sunglasses", "Watch", "Watch", "Watch", "Watch", "Sunglasses"],
["Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes"],
["Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes"],
["Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes"],
["Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots", "Casual Boots"],
["Perfume", "Perfume", "Perfume", "Perfume", "Perfume", "Perfume", "Perfume", "Perfume", "Perfume", "Perfume"],
["Lipstick", "Lipstick", "Lipstick", "Lipstick", "Lipstick", "Lipstick", "Lip Gloss", "Mascara", "Eyeshadow", "Eyeliner"],
["Skincare Cream", "Beauty Cream", "Skincare Cream", "Beauty Cream", "Skincare Cream", "Beauty Cream", "Skincare Cream", "Beauty Cream", "Skincare Cream", "Beauty Cream"],
["Shampoo", "Shampoo", "Shampoo", "Shampoo", "Shampoo", "Shampoo", "Hair Dye Set", "Professional Hairdryer", "Hairstyling Set", "Hairbrush"],
["Dining Table", "Dining Table", "Dining table", "Chair", "Dining Table", "Dining Table", "Chair", "Chair", "Chair", "Kitchen Cupboard"],
["Couch", "Couch", "Couch", "Couch", "Couch", "Couch", "Couch", "Chair", "Chair", "Armchair"],
["Decoration", "Decoration", "Decoration", "Decoration", "Decoration", "Decoration", "Decoration", "Decoration", "Decoration", "Desk Lamp"],
["Pliers", "Drill", "Pliers", "Drill", "Measuring Tape", "Hammer", "Multi Tool", "Multi Tool", "Sanding Machine", "Wrench Kit"],
["Tire", "Tire", "Tire", "Tire", "Tire", "Tire", "Tire", "Tire", "Tire", "Tire"],
["Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil", "Engine Oil"],
["Car Battery", "Car Battery", "Car Battery", "Car Battery", "Car Battery", "Car Battery", "Spark Plug", "Tail Light", "Tail Light", "Front Light"],
["Car Seat", "Car Seat", "Car Seat", "Car Seat", "Car Seat", "Car Seat", "Car Seat", "Car Seat", "Car Seat", "Car Seat", ""],
["Scissors", "Scissors", "Ruler", "Ruler Set", "Pencils", "Pen", "Pen", "Color Pens", "Color Pens", "Stapler"],
["Notebook", "Notebook", "Notebook", "Notebook", "Notebook", "Notebook", "Notebook", "Notebook", "Notebook", "Notebook"],
["Stapler", "Staple", "Sticky Notes", "Sticky Notes", "Pen", "Pen", "Pens", "Pens", "Pen", "A4 Copy Paper "],
["Watercolor", "Bag", "Bag", "Bag", "Bag", "Bag", "Pencil Case", "Color Pens", "Bag", "Bag", "Watercolor"],
["Spinach", "Tomatoes", "Kiwi", "Bananas", "Apple", "Cucumber", "Potatoes", "Lemon", "Avocado", "Kale"],
["Chicken Breast", "Chicken Legs", "Chicken Breasts", "Burger Meat", "Red Meat", "Red Meat", "Red Meat", "Fish Meat", "Fish Meat", "Fish Meat"],
["Milk", "Eggs", "Cheese", "Butter", "Butter", "Cheese", "Cheese", "Milk", "Yogurt", "Yogurt"],
["Bread", "Bread", "Bread", "Bread", "Bread", "Bread", "Bread", "Bread", "Bread", "Bread"],
["Chocolate Bar", "Chocolate Bar", "Chocolate Bar", "Chocolate Bar", "Chocolate Bar", "Chocolate Bar", "Snacks", "Snacks", "Snacks", "Snacks"],
["Cat Food", "Dog Food", "Cat Food", "Dog Food", "Cat Food", "Dog Food", "Cat Food", "Dog Food", "Cat Food", "Dog Food"],
["Diapers", "Diapers", "Diapers", "Diapers", "Diapers", "Diapers", "Diapers", ""],
["Washing Gel Capsule", "Washing Gel Capsule", "Washing Gel Capsule", "Toilet Paper", "Toilet Paper", "Toilet Paper", "Toilet Paper", "Toilet Paper", "Toilet Paper", "Detergent"],
["Paint Brush", "Acrylic Paint", "Watercolor Paint", "Paint Brush", "Paint Brush", "Paint Brush", "Easel", "Easel", "Easel", "Easel", "Watercolor"],
["Classic Guitar", "Ukulele", "Electric Guitar", "Electric Guitar", "Electric Guitar", "Electric Guitar", "Electric Guitar", "Violin", "Saxophone", "French Horn"],
["The Power of Now", "150 Healthiest Foods on Earth", "The Way of the Superior Man", "Seven Habits of Highly Effective People", "Awaken the Giant Within", "No Excuses", "Happiness Hypothesis", "Be Obsessed or Be Average", "Mastery", "Relentless"],
["Kid Toy", "Kid Toy", "Teddy Bear", "Fidget Spinner", "Chess", " Kid Toy", "Toy Car", "Watergun Toy", "Kid Soccerball", " Kid Toy", "Plastic Ship Toy"],
["Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes", "Casual Shoes"],
["Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes", "Sports Shoes"],
["Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes", "Classic Shoes"],
["Leather Boots", "Casual Boots", "Leather Boots", "Casual Boots", "Leather Boots", "Casual Boots", "Leather Boots", "Casual Boots", "Leather Boots", "Casual Boots"]
]
